language: python
sudo: false
dist: xenial
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "3.6"
  - "3.6-dev"
  - "3.7"
  - "3.7-dev"
  - "nightly"
  - "pypy"
  - "pypy3"
env:
  - DJANGO="Django>2.0.0,<3.0.0"    # Django 1.8.x (LTS version)  |   3.4, 3.5, 3.6
  - DJANGO="Django>=1.11.0,<2.0.0"  # Django 1.11.x (LTS version) |   2.7, 3.4, 3.5, 3.6
  - DJANGO="Django>=1.8.0,<1.9.0"   # Django 1.10.x               |   2.7, 3.2 (until the end of 2016), 3.3, 3.4, 3.5
install:
  - pip install --quiet --upgrade -r requirements.txt
  - pip install --quiet --upgrade setuptools wheel
  - pip install --quiet --upgrade "$DJANGO"
matrix:
  exclude:
    - python: "2.7"
      env: DJANGO="Django>2.0.0,<3.0.0"
    - python: "pypy"
      env: DJANGO="Django>2.0.0,<3.0.0"
script:
  - inv test
  - inv build
  - inv test-install
  - inv coverage
after_success:
  - coveralls
notifications:
  email: false
